server:
  servlet:
    port:8080
    contactPath:/api

Spring:
application:
  name:reddit-api
  spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

datasource:
  url:jdbc:postgresql://localhost:3200/reddit
  username:postgres
  password:admin
  driver-class-name:org.postgresql.Driver

jpa:
  properties:
    hibernate:
      temp:
        user_jdbc_metadata_default: false
      databasee-platform: org.hibernate.dialect.PostgresSQL